
version: "3.1"

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - api
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker-volumes/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/scrumbs.app/fullchain.pem:/etc/letsencrypt/live/scrumbs.app/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/scrumbs.app/privkey.pem:/etc/letsencrypt/live/scrumbs.app/privkey.pem
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - scrumbs

  website:
    build:
          context: ./website
          dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    restart: always
    networks:
      - scrumbs

  api:
    build:
          context: ./api
          dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always
    networks:
      - scrumbs

  mongo:
    image: mongo
    expose:
      - "27017"
    volumes:
      - /docker-volumes/data/mongo:/data/db
    networks:
      - scrumbs
      
networks:
  scrumbs:
