
version: "3.1"

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    restart: always
    ports:
      - "80:80"
      - "4200:4200"
      - "4300:4300"
    networks:
      - scrumbs

  api:
    build:
          context: ./api
          dockerfile: Dockerfile
    depends_on:
      - mongo
    restart: always
    networks:
      - scrumbs

  website:
    build:
          context: ./website
          dockerfile: Dockerfile
    depends_on:
      - mongo
    restart: always
    networks:
      - scrumbs

  mongo:
    image: mongo
    expose:
      - "27017"
    networks:
      - scrumbs


networks:
  scrumbs:
