
version: "3.1"

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: nginx/Dockerfile.dev
    depends_on:
      - api
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker-volumes/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/scrumbs.app/fullchain.pem:/etc/letsencrypt/live/scrumbs.app/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/scrumbs.app/privkey.pem:/etc/letsencrypt/live/scrumbs.app/privkey.pem
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - scrumbs

  api:
    build:
          context: ./api
          dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: always
    networks:
      - scrumbs

  mongo:
    image: mongo
    expose:
      - "2717"
    networks:
      - scrumbs

  subscribe:
    build:
      context: ./subscriptions
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    ports:
      - "4000:4000"
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    networks:
      - scrumbs

  postgres:
    image: postgres:9.6.8-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scrumbs-subscribers
    expose:
      - "5432"
    networks:
      - scrumbs
      
networks:
  scrumbs: