
version: "3.1"

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    restart: always
    ports:
      - "80:80"
      - "4200:4200"
      - "4300:4300"
    networks:
      - scrumbs

  api:
    build:
          context: ./api
          dockerfile: Dockerfile
    depends_on:
      - mongo
    restart: always
    networks:
          - scrumbs

  mongo:
    image: mongo
    expose:
      - "2717"
    networks:
          - scrumbs


  subscribe:
    build:
      context: ./subscriptions
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    networks:
          - scrumbs

  postgres:
    image: postgres:9.6.8-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scrumbs-subscribers
    expose:
      - "5432"
    networks:
          - scrumbs

networks:
  scrumbs:
